"""
Django settings for Sodia project.

Generated by "django-admin startproject" using Django 6.0.

Many settings are auto-generated and kept as default, but some are changed.
"""
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()  # loads .env file into environment variables in case this is not run with them already loaded
# (for example if run manually via "python manage.py ..." and not using PyCharm run config)

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    # if run in debug mode and secret key is not defined, use a fallback (not secure)
    SECRET_KEY = os.getenv("DJANGO_SECRET_KEY",
                           "django-insecure-s)x5%2$-gzzbd(q9fd=d#0n+3bp7n8kpd=j_*s-z_ai43$uyrj")  # noqa
else:
    # if not run in debug mode, secret key must be defined
    SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
    if not SECRET_KEY:
        raise ValueError("DJANGO_SECRET_KEY is not set in the environment")
    SECRET_KEY = SECRET_KEY

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")

# Application definition

INSTALLED_APPS = [
    # some built-in apps are removed so that I can implement features myself
    # "django.contrib.auth",             REMOVED DEFAULT (user authentication)
    # "django.contrib.contenttypes",     REMOVED DEFAULT (admin panel)
    # "django.contrib.sessions",         REMOVED DEFAULT (session management)
    # "django.contrib.messages",         REMOVED DEFAULT (flash messages)
    "django.contrib.staticfiles",  # DEFAULT (serve static files in development)

    "django.forms",

    # my apps:
    "users",  # users and sessions handling, login/logout, passwords, etc.
    "settings",
    "api",
    "interactions",  # interactions between users (i.e. friend requests, blocks, and privacy settings adherence)
    "messaging",  # in-app messaging
    "updates",  # polling for updates (i.e. new messages received)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",  # DEFAULT (HSTS & security)
    # "django.contrib.sessions.middleware.SessionMiddleware",     REMOVED DEFAULT (session management)
    "django.middleware.common.CommonMiddleware",  # DEFAULT (basic HTTP behaviour)
    "django.middleware.csrf.CsrfViewMiddleware",  # DEFAULT (CSRF protection)
    # "django.contrib.auth.middleware.AuthenticationMiddleware",  REMOVED DEFAULT (user authentication)
    # "django.contrib.messages.middleware.MessageMiddleware",     REMOVED DEFAULT (flash messages)
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # DEFAULT (X-Frame-Options)

    # my middleware
    "users.middleware.SessionMiddleware",
    "users.middleware.AuthenticationMiddleware",
]

# define location of root config of urls
ROOT_URLCONF = "Sodia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                # "django.contrib.auth.context_processors.auth",          REMOVED DEFAULT (auth)
                # "django.contrib.messages.context_processors.messages",  REMOVED DEFAULT (messages)
            ],
        },
    },
]

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# web server application config
WSGI_APPLICATION = "Sodia.wsgi.application"

# Database
if os.getenv("USE_POSTGRES_DB", None):
    # use PostgreSQL
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "sodia",
            "USER": "sasha",
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": "localhost",
            "PORT": "5432",
        }
    }
else:
    # use SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Internationalization

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)

# static files url
STATIC_URL = "static/"

# directory with static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# view for CSRF protection failed error
CSRF_FAILURE_VIEW = "Sodia.views.csrf_failure"
